/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pharmacy_Menu;

import Doctor_Menu.Doctor_Menu;
import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emirkanmaz
 */
public class Pharmacy_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Pharmacy
     */
    public Pharmacy_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtRef = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtDose = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtNumberTablets = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtLot = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtIssuedDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtExpDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtDailyDose = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jtxtFurtherInformation = new javax.swing.JTextField();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jtxtAdministration = new javax.swing.JTextField();
        jtxtDrivingUsingMachines = new javax.swing.JTextField();
        jtxtHowtoUseMedication = new javax.swing.JTextField();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtDoctorsNHSNo = new javax.swing.JTextField();
        jcmbNameTablets = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnExit = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Name of Item");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Reference No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jtxtRef.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 260, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Dose (mg)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jtxtDose.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Number of Items:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jtxtNumberTablets.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtNumberTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumberTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 260, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("LOT:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jtxtLot.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 260, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Issued Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jtxtIssuedDate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 260, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Exp Date:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jtxtExpDate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 260, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Daily Dose:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtDailyDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDailyDoseActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 260, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Possible Side Effects");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Further Information:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Storage Advice");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Administration");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Driving and Using Machines:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 330, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("How to Use Medication:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Patient ID:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("Doctors NHS No:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, -1));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 360, -1));

        jtxtFurtherInformation.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 360, -1));

        jtxtStorageAdvice.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 360, -1));

        jtxtAdministration.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtAdministration, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 360, -1));

        jtxtDrivingUsingMachines.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtDrivingUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 360, -1));

        jtxtHowtoUseMedication.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 360, -1));

        jtxtPatientID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 360, -1));

        jtxtDoctorsNHSNo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtDoctorsNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 460, 360, -1));

        jcmbNameTablets.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcmbNameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Ibuprofen", "Paracetamol(Parol)", "Paracetamol(Minoset)", "Surgery Mask" }));
        jcmbNameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbNameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 260, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Item", "Reference No", "Dose (mg)", "Number of Item", "LOT", "Issued Date", "Exp Date", "Daily Dose", "Possible Side Effects", "Further Infromation", "Storage Advice", "Administration", "Driving and Using Machines", "How to Use Medication", "Patient ID", "Doctors NHS No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 1330, 220));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 520, 130, 40));

        jbtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 130, 40));

        jbtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 130, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Doctor's Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 160, 40));

        jbtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnLogin.setText("Go Back To Login Menu");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, 240, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNumberTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumberTabletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumberTabletsActionPerformed

    private void jtxtDailyDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDailyDoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDailyDoseActionPerformed

    private void jcmbNameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameTabletsActionPerformed
        if(jcmbNameTablets.getSelectedItem().equals("Ibuprofen")){//, Co-codamol, Paracetamol, Amlodipine
        
            jtxtRef.setText("Ibu005875");
            jtxtDose.setText("2");
            jtxtNumberTablets.setText("32");
            jtxtLot.setText("561005875");
            jtxtIssuedDate.setText("06/10/2021");
            jtxtExpDate.setText("04/05/2023");
            jtxtDailyDose.setText("4");
            jtxtPossibleSideEffects.setText("Sleep and distraction");
            jtxtFurtherInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtAdministration.setText("Yes actioned");
            jtxtDrivingUsingMachines.setText("No");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientID.setText("");
            jtxtDoctorsNHSNo.setText("");
        }
        
        else if(jcmbNameTablets.getSelectedItem().equals("Paracetamol(Parol)")){//, Paracetamol(Parol), Paracetamol(Minoset), Surgery Mask
        
            jtxtRef.setText("Prct86997");
            jtxtDose.setText("500");
            jtxtNumberTablets.setText("20");
            jtxtLot.setText("8699717010109");
            jtxtIssuedDate.setText("08/12/2021");
            jtxtExpDate.setText("15/10/2023");
            jtxtDailyDose.setText("4");
            jtxtPossibleSideEffects.setText("Sleep and distraction");
            jtxtFurtherInformation.setText("Place Dispensary");
                jtxtStorageAdvice.setText("Store at room temperature");
            jtxtAdministration.setText("Yes actioned");
            jtxtDrivingUsingMachines.setText("Yes");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientID.setText("");
            jtxtDoctorsNHSNo.setText("");
        }
        
        if(jcmbNameTablets.getSelectedItem().equals("Paracetamol(Minoset)")){//, Co-codamol, Paracetamol, Amlodipine
        
            jtxtRef.setText("Mnst86997");
            jtxtDose.setText("500");
            jtxtNumberTablets.setText("45");
            jtxtLot.setText("8699546015597");
            jtxtIssuedDate.setText("1/7/2021");
            jtxtExpDate.setText("3/8/2024");
            jtxtDailyDose.setText("4");
            jtxtPossibleSideEffects.setText("Sleep and distraction");
            jtxtFurtherInformation.setText("Place Dispensary");
                jtxtStorageAdvice.setText("Store at room temperature");
            jtxtAdministration.setText("Yes actioned");
            jtxtDrivingUsingMachines.setText("Yes");
            jtxtHowtoUseMedication.setText("Use water, No Alcohol");
            jtxtPatientID.setText("");
            jtxtDoctorsNHSNo.setText("");
        }
        
        if(jcmbNameTablets.getSelectedItem().equals("Surgery Mask")){//, Co-codamol, Paracetamol, Amlodipine
        
            jtxtRef.setText("Mask1234");
            jtxtDose.setText("-----");
            jtxtNumberTablets.setText("3000");
            jtxtLot.setText("8699578656109");
            jtxtIssuedDate.setText("20/12/2021");
            jtxtExpDate.setText("-----");
            jtxtDailyDose.setText("-----");
            jtxtPossibleSideEffects.setText("-----");
            jtxtFurtherInformation.setText("-----");
            jtxtStorageAdvice.setText("-----");
            jtxtAdministration.setText("Yes actioned");
            jtxtDrivingUsingMachines.setText("-----");
            jtxtHowtoUseMedication.setText("-----");
            jtxtPatientID.setText("");
            jtxtDoctorsNHSNo.setText("");
        }
        
        
            
            
    }//GEN-LAST:event_jcmbNameTabletsActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.addRow(new Object[]{jcmbNameTablets.getSelectedItem().toString(), 
        jtxtRef.getText(),jtxtDose.getText() ,jtxtNumberTablets.getText(),jtxtLot.getText(),
        jtxtIssuedDate.getText(), jtxtExpDate.getText(), jtxtDailyDose.getText(),
        jtxtPossibleSideEffects.getText(), jtxtFurtherInformation.getText(), jtxtStorageAdvice.getText(),
        jtxtAdministration.getText(), jtxtDrivingUsingMachines.getText() , jtxtHowtoUseMedication.getText() ,
        jtxtPatientID.getText(), jtxtDoctorsNHSNo.getText(),});
        
        
        
        
        
    }//GEN-LAST:event_jbtnUpdateActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Pharmacy Management System",
                JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                
                JOptionPane.showMessageDialog(null, "No data to delete", "Pharmacy Management System", JOptionPane.OK_OPTION);
            }
            else{
                
                JOptionPane.showMessageDialog(null, "Select a row to delete ", "Pharmacy Management System", JOptionPane.OK_OPTION);
            } 
        }
        else{
            model.removeRow(jTable1.getSelectedRow());
        }
        
   
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        
        Login iLogin = new Login();
        iLogin.setVisible(true);
        
        
        
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Doctor_Menu iDoctor = new Doctor_Menu();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacy_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacy_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacy_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacy_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcmbNameTablets;
    private javax.swing.JTextField jtxtAdministration;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDoctorsNHSNo;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingUsingMachines;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInformation;
    private javax.swing.JTextField jtxtHowtoUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
