/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doctor_Menu;

import Login.Login;
import Pharmacy_Menu.Pharmacy_Menu;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emirkanmaz
 */
public class Doctor_Menu extends javax.swing.JFrame {

    private JFrame frame;
    /**
     * Creates new form Doctor
     */
    public Doctor_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtPhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtFax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtMail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnExit = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jtxtDoctorsNHSNo = new javax.swing.JTextField();
        jcmbDoctorRef = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Doctors Ref No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Doctors NHS No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jtxtName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 290, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Surname");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jtxtSurname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSurnameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 290, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Address of Centre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jtxAddress.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 1080, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Office Phone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jtxtPhone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 340, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Fax No");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jtxtFax.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFaxActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 340, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("E-mail");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jtxtMail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMailActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 520, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctors Ref No.", "NHS No", "Name", "Surname", "Address of Centre", "Office Phone", "Fax No", "E-mail"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 1330, 220));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 520, 130, 40));

        jbtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 130, 40));

        jbtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 130, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Pharmacy M.S.");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 520, 160, 40));

        jbtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnLogin.setText("Go Back To Login Menu");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, -1, 40));

        jtxtDoctorsNHSNo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtDoctorsNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 260, -1));

        jcmbDoctorRef.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcmbDoctorRef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "11111", "22222", "33333", "44444" }));
        jcmbDoctorRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDoctorRefActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbDoctorRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 260, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSurnameActionPerformed

    private void jtxtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMailActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Pharmacy Management System",
            JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){

                JOptionPane.showMessageDialog(null, "No data to delete", "Pharmacy Management System", JOptionPane.OK_OPTION);
            }
            else{

                JOptionPane.showMessageDialog(null, "Select a row to delete ", "Pharmacy Management System", JOptionPane.OK_OPTION);
            }
        }
        else{
            model.removeRow(jTable1.getSelectedRow());
        }

    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[]{jcmbDoctorRef.getSelectedItem().toString(),
            jtxtDoctorsNHSNo.getText(),jtxtName.getText() ,jtxtSurname.getText(),jtxAddress.getText(),
            jtxtPhone.getText(), jtxtFax.getText(), jtxtMail.getText(),});

    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed

        Login iLogin = new Login();
        iLogin.setVisible(true);

    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        Pharmacy_Menu iPharmacy = new Pharmacy_Menu();
        iPharmacy.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jcmbDoctorRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDoctorRefActionPerformed
        if(jcmbDoctorRef.getSelectedItem().equals("11111")){//, Co-codamol, Paracetamol, Amlodipine

            jtxtDoctorsNHSNo.setText("12345");
            jtxtName.setText("Ahmet");
            jtxtSurname.setText("Mehmet");
            jtxAddress.setText("İstanbul Hastane 11111");
            jtxtPhone.setText("533-111-55-11");
            jtxtFax.setText("1511111121");
            jtxtMail.setText("ahmetmehmet@gmail.com");
            
        }

        else if(jcmbDoctorRef.getSelectedItem().equals("22222")){//, Paracetamol(Parol), Paracetamol(Minoset), Surgery Mask

            
            jtxtDoctorsNHSNo.setText("22345");
            jtxtName.setText("Ali");
            jtxtSurname.setText("Hasan");
            jtxAddress.setText("İstanbul Hastane 22222");
            jtxtPhone.setText("533-22-55-22");
            jtxtFax.setText("12223322223");
            jtxtMail.setText("alihasan@gmail.com");
         
        }

        if(jcmbDoctorRef.getSelectedItem().equals("33333")){//, Co-codamol, Paracetamol, Amlodipine

            
            jtxtDoctorsNHSNo.setText("33345");
            jtxtName.setText("Sinan");
            jtxtSurname.setText("Lale");
            jtxAddress.setText("İstanbul Hastane 33333");
            jtxtPhone.setText("533-333-55-33");
            jtxtFax.setText("1233333123");
            jtxtMail.setText("sinanlale@gmail.com");
            
        }

        if(jcmbDoctorRef.getSelectedItem().equals("44444")){//, Co-codamol, Paracetamol, Amlodipine

            
            jtxtDoctorsNHSNo.setText("44445");
            jtxtName.setText("Mustafa");
            jtxtSurname.setText("Ocak");
            jtxAddress.setText("İstanbul Hastane 44444");
            jtxtPhone.setText("533-444-55-44");
            jtxtFax.setText("114442444");
            jtxtMail.setText("MustafaOcak@gmail.com");
            
        }

    }//GEN-LAST:event_jcmbDoctorRefActionPerformed

    private void jtxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPhoneActionPerformed

    private void jtxtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcmbDoctorRef;
    private javax.swing.JTextField jtxAddress;
    private javax.swing.JTextField jtxtDoctorsNHSNo;
    private javax.swing.JTextField jtxtFax;
    private javax.swing.JTextField jtxtMail;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPhone;
    private javax.swing.JTextField jtxtSurname;
    // End of variables declaration//GEN-END:variables
}
